Cherry pick of 76c501b166a24d4514c0212a68d064692ff3a99f failed
stdout:
Auto-merging base_algolia_search/models/ir_model.py
Auto-merging base_algolia_search/__manifest__.py
CONFLICT (content): Merge conflict in base_algolia_search/__manifest__.py

stderr:
21:07:20.501175 git.c:439               trace: built-in: git cherry-pick 76c501b166a24d4514c0212a68d064692ff3a99f
error: could not apply 76c501b... [WIP] Move algolia_search to model._search() to order result_set
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

closes ingadhoc/enterprise-extensions#279

X-original-commit: e4fb8372a2ce90594441ad83ccd1d9fd6ed280bb
Signed-off-by: Juan José Scarafía <jjs@adhoc.com.ar>